### ISSUE TITLE
Tag package version v0.1.0

### ISSUE THREAD

**Issue by juliangehring** [juliangehring/MultipleTesting.jl#19]
New package version for julia 0.5

**Comment by juliangehring** [comment]
@nignatiadis What do you think? Anything else we should also cover with the next minor version?

**Comment by nignatiadis** [comment]
I think you have added more than enough new features and improvements to tag a new minor version!

**Comment by juliangehring** [comment]
Do you think we should aim for a major version 1.0.0 instead?

**Comment by juliangehring** [comment]
Tagged as v0.1.0 with 0443613e379442308b1c5be364d22e632c8eff17

**Comment by juliangehring** [comment]
Closed with https://github.com/JuliaLang/METADATA.jl/pull/7611

**Comment by nignatiadis** [comment]
Cool :D. I think 1.0 should wait until Julia 1.0. But in general getting the combination p-values and allowing some of the adjustment methods to also dispatch on weights would be the main features for the next versions.

Also maybe even start allowing covariates beyond p-values. The regression pi0 estimator of Simina Boca and Jeff Leek (http://biorxiv.org/content/early/2017/01/14/035675) could be a good starting point! (Make it parametrized by λ and `StatsBase.RegressionModel` (or whatever that type is).
