### ISSUE TITLE
Interface redesign?

### ISSUE THREAD

**Issue by juliangehring** [juliangehring/MultipleTesting.jl#61]
A few ideas for a redesign of the user interface:

1. Make the statistic method the first argument, e.g.`foo(method, pvalues, ...)` instead of `foo(pvalues, ..., method)`: Used by other stats packages (e.g. Distributions)
2. Rename `estimate_pi0` to `estimate` (#60), and use `estimate` in other contexts as well (#55)
3. Consistent naming of types representing statistical methods: `Bonferroni` vs `FisherCombination`. 
4. Rename `combine` (#48): Avoid conflicts with existing methods
5. General renaming of methods and types if needed

**Comment by juliangehring** [comment]
Just some ideas from the top of my head. I'm very happy to discuss all of them in more detail.

@nignatiadis What do you think?

**Comment by nignatiadis** [comment]
Sounds good to me! I agree especially with the 1st point, but the 2nd deserves at least some discussion I think (see #59), but probably we should just do it as you proposed!

**Comment by juliangehring** [comment]
What do you think would be the best way to name the statistical methods? At the moment, we mostly use e.g. `BenjaminiHochberg`, but append `Combination` for all the p-value combinations, e.g. `FisherCombination`. I would favour dropping the `Combination` suffix, but does `Fisher` alone become to ambiguous?

**Comment by nignatiadis** [comment]
Hmm, I think Fisher indeed is ambiguous and would prefer to keep calling these Combination, but I agree it is not super elegant.

**Comment by juliangehring** [comment]
We could also go in the other direction, and e.g. turn `BenjaminiHochberg` into `BenjaminiHochbergAdjustment`.

**Comment by harryscholes** [comment]
+1 for point 1.

```julia
adjust(::Type{PValueAdjustment}, pvals::AbstractVector, ...)
```

**Comment by harryscholes** [comment]
I would be very happy to implement the API redesign a la point 1 and my comment above. It would great to get the API in line with other Julia packages. @juliangehring would you be okay with this?

**Comment by juliangehring** [comment]
@harryscholes Thanks for the interest, but I'm don't think that these changes would be beneficial nowadays, and I'd prefer to keep the interface as is.
- Passing the types alone is problematic since some approaches/methods (e.g. `BenjaminiHochbergAdaptive`, `TwoStep`) require additional arguments. Passing instances already addresses this.
- Julia v1 has recommendations regarding [argument ordering](https://docs.julialang.org/en/latest/manual/style-guide/#Write-functions-with-argument-ordering-similar-to-Julia-Base-1), and the current interface aligns with these recommendations ("inputs" before "everything else").
- The style guide also [suggests](https://docs.julialang.org/en/latest/manual/style-guide/#Avoid-confusion-about-whether-something-is-an-instance-or-a-type-1) that using instances over types in method signatures is preferred: "The preferred style is to use instances by default, and only add methods involving Type{MyType} later if they become necessary to solve some problem."

**Comment by harryscholes** [comment]
No problem, sounds good! Thanks for bringing the new style guide to my attention too

**Comment by juliangehring** [comment]
The style guide is fairly new, and I don't think it is widely known so far. But if it gains traction, it might help in getting more consistent interfaces (and other things).
