### ISSUE TITLE
Barber-Candes adjustment breaks if all p-values are < 0.5

### ISSUE THREAD

**Issue by juliangehring** [juliangehring/MultipleTesting.jl#87]
The Barber-Candes adjustment fails with a `BoundError` if all input p-values are < 0.5. For example
```julia
adjust(PValues([0.05, 0.1, 0.3]), BarberCandes())
adjust(PValues([0.01, 0.17, 0.25, 0.37, 0.47]), BarberCandes())
```
both fail with
```
ERROR: BoundsError: attempt to access 3-element Array{Float64,1} at index [4]
Stacktrace:
 [1] adjust(::MultipleTesting.PValues{Float64}, ::MultipleTesting.BarberCandes) at MultipleTesting/src/pval-adjustment.jl:252
```

**Comment by juliangehring** [comment]
@nignatiadis If I understand the method correctly, having values that are greater than 0.5 are essential for the estimation. I think the correct behaviour would be to return `ones(n)` here?

**Comment by nignatiadis** [comment]
Oh nice catch! If all p-values are <0.5 then the estimated FDR is 1/m for all p-values. I will fix it!

The method is similar to BH but with a different numerator, so if you have a p-value equal to $t$, then BH estimates the numerator by $mt$ (=estimated number of false discoveries based on assumption that null p-values are uniformly distributed, so if this is the $k$-th sorted p-value the adjusted p-value modulo monotinization is mt/k), while BC estimates the numerator by 1+ #{p-values >= (1-t)} (using the symmetry of p and 1-p under then null hypothesis). Any p-value >= 0.5 gets assigned an adjusted p-value of 1.

So when everything is <0.5,  1+#{p-values >= (1-t)} =1 always, and now the "largest" p-value has an adjusted p-value of 1/m (and everyone below gets the same by isotonization).

**Comment by juliangehring** [comment]
Ah, I see - thanks for the detailed explanation!

**Comment by juliangehring** [comment]
@nignatiadis #93 should fix this.
